[platformio]
default_envs = esp32s3

[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 921600
upload_speed = 921600
build_flags =
  -DCORE_DEBUG_LEVEL=1
  -DARDUINO_USB_CDC_ON_BOOT=0
  -DCSI_AP_SSID=\"CSI_CAPSTONE_AP\"
  -DCSI_AP_PASSWORD=\"\"

